version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_bot
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
